/**
 * Knowledge Graph Command — CLI for querying codebase knowledge graphs.
 *
 * Subcommands: stats, query, explain, path, diff
 *
 * Operates on `.workflow/codebase/knowledge-graph.json` generated by
 * Understand-Anything or compatible analyzers.
 */

import type { Command } from 'commander';
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { execSync } from 'node:child_process';

import { WikiIndexer } from '#maestro-dashboard/wiki/wiki-indexer.js';
import type { WikiEntry } from '#maestro-dashboard/wiki/wiki-types.js';

// ── Types ──────────────────────────────────────────────────────────────

interface GraphNode {
  id: string;
  type: string;
  name: string;
  filePath?: string;
  summary: string;
  tags: string[];
  complexity?: string;
}

interface GraphEdge {
  source: string;
  target: string;
  type: string;
  direction?: string;
  description?: string;
  weight?: number;
}

interface Layer {
  id: string;
  name: string;
  description: string;
  nodeIds: string[];
}

interface TourStep {
  order: number;
  title: string;
  description: string;
  nodeIds: string[];
  languageLesson?: string;
}

interface KnowledgeGraph {
  version: string;
  project: {
    name: string;
    languages: string[];
    frameworks: string[];
    description: string;
    analyzedAt: string;
    gitCommitHash?: string;
  };
  nodes: GraphNode[];
  edges: GraphEdge[];
  layers: Layer[];
  tour: TourStep[];
}

// ── Helpers ────────────────────────────────────────────────────────────

const KG_PATH = '.workflow/codebase/knowledge-graph.json';

function loadGraph(): KnowledgeGraph {
  const fullPath = resolve(KG_PATH);
  if (!existsSync(fullPath)) {
    console.error(`Knowledge graph not found: ${fullPath}`);
    console.error('  Hint: generate one with Understand-Anything or a compatible analyzer');
    process.exit(1);
  }
  try {
    const raw = readFileSync(fullPath, 'utf-8');
    return JSON.parse(raw) as KnowledgeGraph;
  } catch (err) {
    console.error(`Failed to parse knowledge graph: ${(err as Error).message}`);
    process.exit(1);
  }
}

function truncate(text: string, maxLen: number): string {
  if (!text) return '';
  if (text.length <= maxLen) return text;
  return text.slice(0, maxLen - 3) + '...';
}

function countBy<T>(items: T[], keyFn: (item: T) => string): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const item of items) {
    const key = keyFn(item);
    counts[key] = (counts[key] ?? 0) + 1;
  }
  return counts;
}

// ── Wiki cross-reference ──────────────────────────────────────────────

let _wikiIndexer: WikiIndexer | null = null;
function getWikiIndexer(): WikiIndexer | null {
  if (_wikiIndexer) return _wikiIndexer;
  const workflowRoot = resolve('.workflow');
  if (!existsSync(workflowRoot)) return null;
  _wikiIndexer = new WikiIndexer({ workflowRoot });
  return _wikiIndexer;
}

interface WikiMatch {
  id: string;
  type: string;
  title: string;
  matchReason: string;
}

async function findRelatedWikiEntries(nodeId: string, filePath?: string): Promise<WikiMatch[]> {
  const indexer = getWikiIndexer();
  if (!indexer) return [];
  try {
    const index = await indexer.get();
    const matches: WikiMatch[] = [];
    const seen = new Set<string>();

    for (const e of index.entries) {
      if (seen.has(e.id)) continue;
      // Match by KG node binding (uakg-* entries referencing this node)
      if (e.ext?.virtualKind === 'ua-kg-node' && e.ext?.kgNodeId === nodeId) {
        seen.add(e.id);
        matches.push({ id: e.id, type: e.type, title: e.title, matchReason: 'kg-node-entry' });
        continue;
      }
      // Match by codePaths containing the node's filePath
      if (filePath && Array.isArray(e.ext?.codeLocations)) {
        const locs = e.ext.codeLocations as string[];
        const normFp = filePath.replace(/\\/g, '/').toLowerCase();
        if (locs.some(l => l.replace(/\\/g, '/').toLowerCase() === normFp)) {
          seen.add(e.id);
          matches.push({ id: e.id, type: e.type, title: e.title, matchReason: 'codePath-match' });
        }
      }
      // Match by codePaths in ext.codePaths (knowhow entries)
      if (filePath && Array.isArray(e.ext?.codePaths)) {
        const paths = e.ext.codePaths as string[];
        const normFp = filePath.replace(/\\/g, '/').toLowerCase();
        if (paths.some(p => p.replace(/\\/g, '/').toLowerCase() === normFp)) {
          seen.add(e.id);
          matches.push({ id: e.id, type: e.type, title: e.title, matchReason: 'codePath-match' });
        }
      }
    }
    return matches;
  } catch {
    return [];
  }
}

// ── Registration ───────────────────────────────────────────────────────

export function registerKgCommand(program: Command): void {
  const kg = program
    .command('kg')
    .description('Query codebase knowledge graph (.workflow/codebase/knowledge-graph.json)');

  // ── stats ──────────────────────────────────────────────────────────
  kg
    .command('stats')
    .description('Display knowledge graph statistics')
    .option('--json', 'Output as JSON')
    .action((_opts) => {
      const graph = loadGraph();
      const nodesByType = countBy(graph.nodes, n => n.type);
      const edgesByType = countBy(graph.edges, e => e.type);

      const data = {
        project: graph.project.name,
        version: graph.version,
        nodes: { total: graph.nodes.length, byType: nodesByType },
        edges: { total: graph.edges.length, byType: edgesByType },
        layers: graph.layers.length,
        tourSteps: graph.tour.length,
      };

      if (_opts.json) {
        console.log(JSON.stringify(data, null, 2));
        return;
      }

      console.log(`Knowledge Graph: ${data.project} (v${data.version})`);
      console.log('');
      console.log(`Nodes: ${data.nodes.total}`);
      for (const [type, count] of Object.entries(nodesByType)) {
        console.log(`  ${type}: ${count}`);
      }
      console.log('');
      console.log(`Edges: ${data.edges.total}`);
      for (const [type, count] of Object.entries(edgesByType)) {
        console.log(`  ${type}: ${count}`);
      }
      console.log('');
      console.log(`Layers: ${data.layers}`);
      console.log(`Tour steps: ${data.tourSteps}`);
    });

  // ── query ──────────────────────────────────────────────────────────
  kg
    .command('query <text>')
    .description('Search nodes by name, summary, or tags')
    .option('--limit <n>', 'Max results', '10')
    .option('--type <nodeType>', 'Filter by node type')
    .option('--json', 'Output as JSON')
    .action((text: string, opts) => {
      const graph = loadGraph();
      const needle = text.toLowerCase();
      const limit = Number(opts.limit) || 10;

      let matches = graph.nodes.filter(n => {
        const haystack = [
          n.name,
          n.summary,
          ...(n.tags ?? []),
        ].join(' ').toLowerCase();
        return haystack.includes(needle);
      });

      if (opts.type) {
        const typeFilter = opts.type.toLowerCase();
        matches = matches.filter(n => n.type.toLowerCase() === typeFilter);
      }

      const limited = matches.slice(0, limit);

      if (opts.json) {
        console.log(JSON.stringify({ query: text, total: matches.length, nodes: limited }, null, 2));
        return;
      }

      console.log(`Query: "${text}"  (${limited.length}/${matches.length} results)`);
      for (const n of limited) {
        console.log(`  [${n.type}] ${n.id} -- ${truncate(n.summary, 80)}`);
      }
    });

  // ── explain ────────────────────────────────────────────────────────
  kg
    .command('explain <node-id>')
    .description('Show full details of a node and its connections')
    .option('--json', 'Output as JSON')
    .option('--no-wiki', 'Skip wiki cross-reference lookup')
    .action(async (nodeId: string, opts) => {
      const graph = loadGraph();
      const node = graph.nodes.find(n => n.id === nodeId);

      if (!node) {
        console.error(`Node not found: ${nodeId}`);
        process.exit(1);
      }

      const incoming = graph.edges.filter(e => e.target === nodeId);
      const outgoing = graph.edges.filter(e => e.source === nodeId);
      const layers = graph.layers.filter(l => l.nodeIds.includes(nodeId));

      const wikiMatches = opts.wiki !== false
        ? await findRelatedWikiEntries(nodeId, node.filePath)
        : [];

      if (opts.json) {
        console.log(JSON.stringify({ node, incoming, outgoing, layers, wiki: wikiMatches }, null, 2));
        return;
      }

      console.log(`Node: ${node.id}`);
      console.log(`  Type:       ${node.type}`);
      console.log(`  Name:       ${node.name}`);
      if (node.filePath) console.log(`  File:       ${node.filePath}`);
      console.log(`  Summary:    ${node.summary}`);
      if (node.tags?.length) console.log(`  Tags:       ${node.tags.join(', ')}`);
      if (node.complexity) console.log(`  Complexity: ${node.complexity}`);

      if (layers.length > 0) {
        console.log('');
        console.log('Layers:');
        for (const l of layers) {
          console.log(`  ${l.id} -- ${l.name}`);
        }
      }

      if (incoming.length > 0) {
        console.log('');
        console.log(`Incoming edges (${incoming.length}):`);
        for (const e of incoming) {
          console.log(`  ${e.source} --${e.type}--> ${nodeId}`);
        }
      }

      if (outgoing.length > 0) {
        console.log('');
        console.log(`Outgoing edges (${outgoing.length}):`);
        for (const e of outgoing) {
          console.log(`  ${nodeId} --${e.type}--> ${e.target}`);
        }
      }

      if (wikiMatches.length > 0) {
        console.log('');
        console.log(`Related wiki entries (${wikiMatches.length}):`);
        for (const w of wikiMatches) {
          console.log(`  [${w.type}] ${w.id} -- ${w.title} (${w.matchReason})`);
        }
      }
    });

  // ── path ───────────────────────────────────────────────────────────
  kg
    .command('path <from-id> <to-id>')
    .description('Find shortest path between two nodes (BFS, undirected)')
    .option('--json', 'Output as JSON')
    .action((fromId: string, toId: string, opts) => {
      const graph = loadGraph();

      // Validate nodes exist
      const fromNode = graph.nodes.find(n => n.id === fromId);
      const toNode = graph.nodes.find(n => n.id === toId);
      if (!fromNode) {
        console.error(`Source node not found: ${fromId}`);
        process.exit(1);
      }
      if (!toNode) {
        console.error(`Target node not found: ${toId}`);
        process.exit(1);
      }

      // Build adjacency list (undirected)
      const adj = new Map<string, Array<{ neighbor: string; edge: GraphEdge }>>();
      for (const e of graph.edges) {
        if (!adj.has(e.source)) adj.set(e.source, []);
        if (!adj.has(e.target)) adj.set(e.target, []);
        adj.get(e.source)!.push({ neighbor: e.target, edge: e });
        adj.get(e.target)!.push({ neighbor: e.source, edge: e });
      }

      // BFS
      const visited = new Set<string>();
      const parent = new Map<string, { node: string; edge: GraphEdge }>();
      const queue: string[] = [fromId];
      visited.add(fromId);
      let found = false;

      while (queue.length > 0) {
        const current = queue.shift()!;
        if (current === toId) {
          found = true;
          break;
        }
        for (const { neighbor, edge } of adj.get(current) ?? []) {
          if (!visited.has(neighbor)) {
            visited.add(neighbor);
            parent.set(neighbor, { node: current, edge });
            queue.push(neighbor);
          }
        }
      }

      if (!found) {
        if (opts.json) {
          console.log(JSON.stringify({ from: fromId, to: toId, path: null, message: 'No path found' }, null, 2));
        } else {
          console.log(`No path found from ${fromId} to ${toId}`);
        }
        return;
      }

      // Reconstruct path
      const pathNodes: string[] = [];
      const pathEdges: GraphEdge[] = [];
      let cur = toId;
      while (cur !== fromId) {
        pathNodes.unshift(cur);
        const p = parent.get(cur)!;
        pathEdges.unshift(p.edge);
        cur = p.node;
      }
      pathNodes.unshift(fromId);

      if (opts.json) {
        const steps = pathNodes.map((nid, i) => {
          const n = graph.nodes.find(nd => nd.id === nid);
          return {
            node: nid,
            type: n?.type,
            name: n?.name,
            edgeToNext: i < pathEdges.length ? pathEdges[i].type : undefined,
          };
        });
        console.log(JSON.stringify({ from: fromId, to: toId, length: pathEdges.length, steps }, null, 2));
        return;
      }

      console.log(`Path: ${fromId} -> ${toId}  (${pathEdges.length} hops)`);
      console.log('');
      for (let i = 0; i < pathNodes.length; i++) {
        const n = graph.nodes.find(nd => nd.id === pathNodes[i]);
        console.log(`  [${n?.type ?? '?'}] ${pathNodes[i]} -- ${truncate(n?.name ?? '', 60)}`);
        if (i < pathEdges.length) {
          console.log(`    | ${pathEdges[i].type}`);
        }
      }
    });

  // ── diff ───────────────────────────────────────────────────────────
  kg
    .command('diff')
    .description('Show KG nodes affected by git changes')
    .option('--staged', 'Use staged changes only')
    .option('--json', 'Output as JSON')
    .action((opts) => {
      const graph = loadGraph();

      // Get changed files from git
      let changedFiles: string[];
      try {
        const cmd = opts.staged
          ? 'git diff --staged --name-only'
          : 'git diff --name-only';
        const output = execSync(cmd, { encoding: 'utf-8' }).trim();
        changedFiles = output ? output.split('\n').map(f => f.trim()).filter(Boolean) : [];
      } catch {
        console.error('Failed to run git diff. Are you in a git repository?');
        process.exit(1);
      }

      if (changedFiles.length === 0) {
        if (opts.json) {
          console.log(JSON.stringify({ changedFiles: [], direct: [], impacted: [] }, null, 2));
        } else {
          console.log('No changed files detected.');
        }
        return;
      }

      // Find direct nodes (filePath matches a changed file)
      const directNodes = graph.nodes.filter(n =>
        n.filePath && changedFiles.some(f => n.filePath === f || n.filePath!.endsWith('/' + f) || f.endsWith('/' + n.filePath!)),
      );
      const directIds = new Set(directNodes.map(n => n.id));

      // Expand 1 hop: find all directly connected nodes
      const impactedIds = new Set<string>();
      for (const e of graph.edges) {
        if (directIds.has(e.source) && !directIds.has(e.target)) {
          impactedIds.add(e.target);
        }
        if (directIds.has(e.target) && !directIds.has(e.source)) {
          impactedIds.add(e.source);
        }
      }

      const impactedNodes = graph.nodes.filter(n => impactedIds.has(n.id));

      if (opts.json) {
        console.log(JSON.stringify({
          changedFiles,
          direct: directNodes,
          impacted: impactedNodes,
        }, null, 2));
        return;
      }

      console.log(`Changed files: ${changedFiles.length}`);
      console.log('');

      console.log(`Direct (${directNodes.length}):`);
      if (directNodes.length === 0) {
        console.log('  (no KG nodes match changed files)');
      } else {
        for (const n of directNodes) {
          console.log(`  [${n.type}] ${n.id} -- ${truncate(n.summary, 60)}`);
        }
      }

      console.log('');
      console.log(`Impacted (${impactedNodes.length}):`);
      if (impactedNodes.length === 0) {
        console.log('  (no 1-hop neighbors found)');
      } else {
        for (const n of impactedNodes) {
          console.log(`  [${n.type}] ${n.id} -- ${truncate(n.summary, 60)}`);
        }
      }
    });

  // ── diff-wiki ─────────────────────────────────────────────────────
  kg
    .command('diff-wiki')
    .description('Cross-reference git changes with KG nodes and wiki entries')
    .option('--staged', 'Use staged changes only')
    .option('--json', 'Output as JSON')
    .action(async (opts) => {
      const graph = loadGraph();

      let changedFiles: string[];
      try {
        const cmd = opts.staged
          ? 'git diff --staged --name-only'
          : 'git diff --name-only';
        const output = execSync(cmd, { encoding: 'utf-8' }).trim();
        changedFiles = output ? output.split('\n').map(f => f.trim()).filter(Boolean) : [];
      } catch {
        console.error('Failed to run git diff. Are you in a git repository?');
        process.exit(1);
      }

      if (changedFiles.length === 0) {
        if (opts.json) {
          console.log(JSON.stringify({ changedFiles: [], affectedWiki: [] }, null, 2));
        } else {
          console.log('No changed files detected.');
        }
        return;
      }

      // Find direct + impacted KG nodes
      const directNodes = graph.nodes.filter(n =>
        n.filePath && changedFiles.some(f =>
          n.filePath === f || n.filePath!.endsWith('/' + f) || f.endsWith('/' + n.filePath!)),
      );
      const directIds = new Set(directNodes.map(n => n.id));
      const impactedIds = new Set<string>();
      for (const e of graph.edges) {
        if (directIds.has(e.source) && !directIds.has(e.target)) impactedIds.add(e.target);
        if (directIds.has(e.target) && !directIds.has(e.source)) impactedIds.add(e.source);
      }

      // Collect all affected file paths from KG nodes
      const affectedPaths = new Set<string>();
      for (const n of directNodes) {
        if (n.filePath) affectedPaths.add(n.filePath.replace(/\\/g, '/').toLowerCase());
      }
      for (const nid of impactedIds) {
        const n = graph.nodes.find(nd => nd.id === nid);
        if (n?.filePath) affectedPaths.add(n.filePath.replace(/\\/g, '/').toLowerCase());
      }
      // Also add raw changed files
      for (const f of changedFiles) {
        affectedPaths.add(f.replace(/\\/g, '/').toLowerCase());
      }

      // Cross-reference with wiki
      const indexer = getWikiIndexer();
      const affectedWiki: Array<{ id: string; type: string; title: string; reason: string }> = [];

      if (indexer) {
        try {
          const index = await indexer.get();
          const seen = new Set<string>();
          for (const entry of index.entries) {
            if (seen.has(entry.id)) continue;
            // Check codeLocations (codebase-component entries)
            if (Array.isArray(entry.ext?.codeLocations)) {
              const locs = entry.ext.codeLocations as string[];
              for (const loc of locs) {
                if (affectedPaths.has(loc.replace(/\\/g, '/').toLowerCase())) {
                  seen.add(entry.id);
                  affectedWiki.push({ id: entry.id, type: entry.type, title: entry.title, reason: 'codeLocation' });
                  break;
                }
              }
            }
            if (seen.has(entry.id)) continue;
            // Check codePaths (knowhow entries)
            if (Array.isArray(entry.ext?.codePaths)) {
              const paths = entry.ext.codePaths as string[];
              for (const p of paths) {
                if (affectedPaths.has(p.replace(/\\/g, '/').toLowerCase())) {
                  seen.add(entry.id);
                  affectedWiki.push({ id: entry.id, type: entry.type, title: entry.title, reason: 'codePath' });
                  break;
                }
              }
            }
          }
        } catch { /* wiki unavailable — continue without */ }
      }

      if (opts.json) {
        console.log(JSON.stringify({
          changedFiles,
          directNodes: directNodes.length,
          impactedNodes: impactedIds.size,
          affectedWiki,
        }, null, 2));
        return;
      }

      console.log(`Changed files: ${changedFiles.length}`);
      console.log(`KG direct: ${directNodes.length}, impacted: ${impactedIds.size}`);
      console.log('');

      if (affectedWiki.length === 0) {
        console.log('No wiki entries affected by these changes.');
      } else {
        console.log(`Affected wiki entries (${affectedWiki.length}):`);
        for (const w of affectedWiki) {
          console.log(`  [${w.type}] ${w.id} -- ${w.title} (${w.reason})`);
        }
      }
    });
}
